/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpn;

import rpn.cmd.Cmd;

public class App {

    public static void main(String[] args) {
        CalApp cal = new Cmd();
        cal.start();
    }
}
